#pragma once

#include <../../extern/pocketfft/pocketfft_hdronly.h>
#include <algorithm>
#include <cmath>
#include <common/channel.hpp>
#include <common/constants.hpp>
#include <complex>
#include <processing/iprocessor.hpp>
#include <string>
#include <vector>

namespace Scoped {

class MeasurementProcessor : public IVirtualProcessor {
private:
  bool m_enabled = false;
  std::string m_name;
  std::string m_source_label = "CH1";

  float m_vertical_scale = Constants::DEFAULT_VERTICAL_SCALE;
  float m_vertical_offset = Constants::DEFAULT_VERTICAL_OFFSET;
  size_t m_horizontal_scale = Constants::DEFAULT_HORIZONTAL_SCALE;
  size_t m_horizontal_offset = Constants::DEFAULT_HORIZONTAL_OFFSET;
  Color m_color = {1.0f, 1.0f, 1.0f, 1.0f};
  bool m_show_in_popup = false;

  // Measured values
  float m_v_pp = 0.0f;
  float m_v_rms = 0.0f;
  float m_v_avg = 0.0f;
  float m_v_min = 0.0f;
  float m_v_max = 0.0f;
  float m_freq = 0.0f;
  float m_period = 0.0f;

public:
  explicit MeasurementProcessor(const std::string &name) : m_name(name) {}

  // Accessors
  std::string getName() const override { return m_name; }
  bool isEnabled() const override { return m_enabled; }
  ProcessorType getType() const override { return ProcessorType::Measurement; }
  float getVerticalScale() const override { return m_vertical_scale; }
  float getVerticalOffset() const override { return m_vertical_offset; }
  size_t getHorizontalScale() const override { return m_horizontal_scale; }
  size_t getHorizontalOffset() const override { return m_horizontal_offset; }
  Color getColor() const override { return m_color; }

  std::string getSourceLabel() const { return m_source_label; }

  // Setters
  void setEnabled(bool enabled) override { m_enabled = enabled; }
  void setVerticalScale(float scale) override { m_vertical_scale = scale; }
  void setVerticalOffset(float offset) override { m_vertical_offset = offset; }
  void setHorizontalScale(size_t scale) override { m_horizontal_scale = scale; }
  void setHorizontalOffset(size_t offset) override {
    m_horizontal_offset = offset;
  }
  void setColor(const Color &color) override { m_color = color; }

  void setSourceLabel(const std::string &label) { m_source_label = label; }
  void setShowInPopup(bool show) { m_show_in_popup = show; }

  // Accessors for measured values
  bool getShowInPopup() const { return m_show_in_popup; }
  float getVpp() const { return m_v_pp; }
  float getVrms() const { return m_v_rms; }
  float getVavg() const { return m_v_avg; }
  float getVmin() const { return m_v_min; }
  float getVmax() const { return m_v_max; }
  float getFreq() const { return m_freq; }
  float getPeriod() const { return m_period; }

  // Pipeline
  void process(const std::vector<IChannel *> &sources,
               std::vector<Trace> &traces, size_t trigger_in_frame) override {
    if (!m_enabled)
      return;

    const std::vector<float> *raw_frame_ptr = nullptr;

    // 1. Check if the source is a trace generated by a prior processor
    for (const auto &trace : traces) {
      if (trace.name.find(m_source_label) == 0) { // Starts with m_source_label
        raw_frame_ptr = &trace.data;
        break;
      }
    }

    // 2. If not found in traces, check raw channels
    if (!raw_frame_ptr) {
      for (auto *ch : sources) {
        if (ch->getLabel() == m_source_label) {
          raw_frame_ptr = &ch->getRawFrame();
          break;
        }
      }
    }

    if (!raw_frame_ptr || raw_frame_ptr->empty()) {
      m_v_pp = 0.0f;
      m_v_rms = 0.0f;
      m_v_avg = 0.0f;
      m_v_min = 0.0f;
      m_v_max = 0.0f;
      m_freq = 0.0f;
      m_period = 0.0f;
      return;
    }

    const auto &raw_frame = *raw_frame_ptr;

    calculateVpp(raw_frame);
    calculateVRMS(raw_frame);
    calculateVavg(raw_frame);
    calculateVmin(raw_frame);
    calculateVmax(raw_frame);
    calculateFreqAndPeriod(raw_frame);
  }

  void calculateVpp(const std::vector<float> &frame) {
    if (frame.empty()) {
      m_v_pp = 0.0f;
      return;
    }

    float min_val = frame[0];
    float max_val = frame[0];

    for (size_t i = 1; i < frame.size(); ++i) {
      if (frame[i] < min_val)
        min_val = frame[i];
      if (frame[i] > max_val)
        max_val = frame[i];
    }

    m_v_pp = max_val - min_val;
  }

  void calculateVRMS(const std::vector<float> &frame) {
    if (frame.empty()) {
      m_v_rms = 0.0f;
      return;
    }

    float sum_sq = 0.0f;
    for (size_t i = 0; i < frame.size(); ++i) {
      sum_sq += frame[i] * frame[i];
    }

    m_v_rms = std::sqrt(sum_sq / frame.size());
  }

  void calculateVavg(const std::vector<float> &frame) {
    if (frame.empty()) {
      m_v_avg = 0.0f;
      return;
    }

    float sum = 0.0f;
    for (size_t i = 0; i < frame.size(); ++i) {
      sum += frame[i];
    }

    m_v_avg = sum / frame.size();
  }

  void calculateVmin(const std::vector<float> &frame) {
    if (frame.empty()) {
      m_v_min = 0.0f;
      return;
    }

    float min_val = frame[0];
    for (size_t i = 1; i < frame.size(); ++i) {
      if (frame[i] < min_val)
        min_val = frame[i];
    }

    m_v_min = min_val;
  }

  void calculateVmax(const std::vector<float> &frame) {
    if (frame.empty()) {
      m_v_max = 0.0f;
      return;
    }

    float max_val = frame[0];
    for (size_t i = 1; i < frame.size(); ++i) {
      if (frame[i] > max_val)
        max_val = frame[i];
    }

    m_v_max = max_val;
  }

  // FFT implementation
  void calculateFreqAndPeriod(const std::vector<float>& frame) {
      m_freq = 0.0f;
      m_period = 0.0f;

      const size_t N = frame.size();

      if (N < 16)
          return;

      const float sample_rate =
          static_cast<float>(Constants::ADC_SAMPLE_RATE_HZ);

      // Remove DC offset
      float mean = 0.0f;

      for (float v : frame)
          mean += v;

      mean /= static_cast<float>(N);

      std::vector<float> centered(N);

      float energy = 0.0f;

      for (size_t i = 0; i < N; ++i) {
          centered[i] = frame[i] - mean;
          energy += centered[i] * centered[i];
      }

      // No useful signal
      if (energy <= 1e-12f)
          return;


      // Zero-pad to 2N
      size_t fft_size = 1;

      while (fft_size < 2 * N)
          fft_size <<= 1;


      // Prepare complex FFT input
      std::vector<std::complex<float>> fft_data(fft_size);

      for (size_t i = 0; i < N; ++i)
          fft_data[i] = std::complex<float>(centered[i], 0.0f);

      for (size_t i = N; i < fft_size; ++i)
          fft_data[i] = std::complex<float>(0.0f, 0.0f);

      // Forward FFT
      pocketfft::shape_t shape{fft_size};

      pocketfft::stride_t stride{
          static_cast<std::ptrdiff_t>(sizeof(std::complex<float>))
      };

      pocketfft::shape_t axes{0};

      pocketfft::c2c(
          shape,
          stride,
          stride,
          axes,
          pocketfft::FORWARD,
          fft_data.data(),
          fft_data.data(),
          1.0f
      );

      // Convert FFT into power spectrum
      // X[k] * conj(X[k])
      for (size_t k = 0; k < fft_size; ++k) {
          fft_data[k] =
              fft_data[k] * std::conj(fft_data[k]);
      }

      // Inverse FFT
      const float inverse_scale =
          1.0f / static_cast<float>(fft_size);

      pocketfft::c2c(
          shape,
          stride,
          stride,
          axes,
          pocketfft::BACKWARD,
          fft_data.data(),
          fft_data.data(),
          inverse_scale
      );


      // Determine useful lag range
      // lag = samples between repeated waveform features
      const size_t min_lag = 2;
      const size_t max_lag = N / 2;

      if (max_lag <= min_lag)
          return;


      // Normalize autocorrelation
      std::vector<float> correlation(max_lag + 1);

      const float zero_lag =
          fft_data[0].real();

      if (zero_lag <= 1e-12f)
          return;

      for (size_t lag = 0; lag <= max_lag; ++lag) {
          correlation[lag] =
              fft_data[lag].real() / zero_lag;
      }

      // Find the first strong autocorrelation peak
      constexpr float MIN_CORRELATION = 0.50f;

      size_t best_lag = 0;

      for (size_t lag = min_lag + 1;
          lag < max_lag;
          ++lag) {

          const float previous = correlation[lag - 1];
          const float current  = correlation[lag];
          const float next     = correlation[lag + 1];

          // Must be a local maximum
          if (current < previous)
              continue;

          if (current < next)
              continue;

          // Must be sufficiently periodic
          if (current >= MIN_CORRELATION) {
              best_lag = lag;
              break;
          }
      }

      // No sufficiently strong periodicity
      if (best_lag == 0)
          return;

      // Parabolic interpolation
      float refined_lag =
          static_cast<float>(best_lag);

      const float ym1 =
          correlation[best_lag - 1];

      const float y0 =
          correlation[best_lag];

      const float yp1 =
          correlation[best_lag + 1];

      const float denominator =
          ym1 - 2.0f * y0 + yp1;

      if (std::abs(denominator) > 1e-12f) {

          float delta =
              0.5f * (ym1 - yp1) / denominator;

          // Prevent pathological interpolation
          delta = std::clamp(delta, -0.5f, 0.5f);

          refined_lag += delta;
      }

      // Convert period to frequency
      if (refined_lag <= 0.0f)
          return;

      m_period =
          refined_lag / sample_rate;

      m_freq =
          sample_rate / refined_lag;
    }

  };

} // namespace Scoped
